SubzGenerator/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  root 'welcome#index'

  get '/file_upload/index', to: 'file_upload#index'
  post '/file_upload/index', to: 'file_upload#create'
  get 'download_srt/download_subtitles'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

SubzGenerator/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

SubzGenerator/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

   def self.connect_to_linkedin(auth, signed_in_resource=nil)
     user = User.where(:provider => auth.provider, :uid => auth.uid).first
     if user
       return user
     else
       registered_user = User.where(:email => auth.info.email).first
       if registered_user
         return registered_user
       else
         user = User.create( provider:auth.provider,
                             uid:auth.uid,
                             email:auth.info.email,
                             password:Devise.friendly_token[0,20],
                           )
       end
     end
   end
   
   def self.find_for_twitter_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    if user
      return user
    else
      registered_user = User.where(:email => auth.uid + "@twitter.com").first
      if registered_user
        return registered_user
      else

        user = User.create( provider:auth.provider,
                            uid:auth.uid,
                            email:auth.uid+"@twitter.com",
                            password:Devise.friendly_token[0,20],
                          )
      end

    end
  end
end

SubzGenerator/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in) do |user_params|
      user_params.permit(:username, :email)
    end
  end
end

SubzGenerator/app/controllers/download_srt_controller.rb
class DownloadSrtController < ApplicationController
  def download_subtitles
    file = File.open(Rails.root.join('public', 'generated_subtitles', "#{params[:filename_param]}.srt"), "rb")
    contents = file.read
    file.close

    File.delete(file.path) if File.exist?(file.path)

    send_data(contents, :filename => "#{params[:filename_param]}.srt")
  end
end

SubzGenerator/app/controllers/file_upload_controller.rb
require_relative "./video_services/convert_video.rb"
require_relative "./video_services/audio_to_text.rb"

class FileUploadController < ApplicationController
	before_action :authenticate_user!
	def index
	end

	def new
	end

	def create
		name = params[:upload][:file].original_filename
		directory = "public/data"
		path = File.join(directory, name)
		if not File.exists? directory
		  `mkdir "#{directory}"`
		end
		File.open(path, "wb") { |f| f.write(params[:upload][:file].read) }
		filename = to_flac(path)
		json_data_to_srt(filename, get_json_data("public/converted_data/#{filename}.flac"), params[:upload][:lang])
		File.delete("public/converted_data/#{filename}.flac") if File.exist?("public/converted_data/#{filename}.flac")
		File.delete("public/data/#{filename}.mp4") if File.exist?("public/data/#{filename}.mp4")
		redirect_to :controller => :download_srt, :action => 'download_subtitles', :filename_param => filename
	end
end

SubzGenerator/app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def linkedin
    auth = env["omniauth.auth"]
    @user = User.connect_to_linkedin(request.env["omniauth.auth"],current_user)
    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.linkedin_uid"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
  
  def twitter
    auth = env["omniauth.auth"]

    @user = User.find_for_twitter_oauth(request.env["omniauth.auth"],current_user)
    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.twitter_uid"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
	
  end
end

SubzGenerator/app/controllers/video_services/audio_to_text.rb
require 'json'
require_relative './translate.rb'
def get_json_data(pathToFile)
	response = `curl -X POST -u 6b832e7b-a64a-4031-a7f9-118b551bb1d1:oLMdskNywb3T https://stream.watsonplatform.net/speech-to-text/api/v1/recognize?timestamps=true --header \"Content-Type: audio/flac\" --data-binary @#{pathToFile}`
	JSON.parse(response)
end

def json_data_to_srt(filename, json_data, language)
	if not File.exists? "public/generated_subtitles/"
    `mkdir public/generated_subtitles/`
  end
	file_exist?("public/generated_subtitles/#{filename}.srt")
	counter = 0
	snippets = json_data['results']
	snippets.each do |snippet|
		counter += 1
		sentence = translatee(snippet['alternatives'][0]['transcript'].to_s, language).to_s
		write_to_file(filename, counter, snippet, sentence)
	end
end

def convert_time(seconds)
	Time.at(seconds).utc.strftime("%H:%M:%S")
end

def file_exist?(file)
	if File.exist?(file) == true
		File.delete(file)
	end
end

def write_to_file(filename, paragraph_counter, snippet, sentence)
	open(Rails.public_path.join("generated_subtitles/#{filename}.srt"), "a") do |f|
		f << paragraph_counter.to_s
		f << "\n"
		f << subtitle_time_range(snippet)
		f << sentence
		f << "\n\n"
	end
end

def subtitle_time_range(snippet)
	"#{convert_time(snippet['alternatives'][0]['timestamps'].first[1])},000 --> #{convert_time(snippet['alternatives'][0]['timestamps'].last[2])},000\n"
end

SubzGenerator/app/controllers/video_services/convert_video.rb
def convert(pathToFile, format)
	filename = pathToFile.split(".").first.to_s.split("/").last.to_s
  if not File.exists? "public/converted_data/"
    `mkdir public/converted_data/`
  end
	system("ffmpeg -i #{pathToFile} public/converted_data/#{filename}.#{format}")
	if $?.success?
		puts "Converted successfully!"
	else
		puts "Something went wrong..."
	end
  filename
end

def to_flac(pathToFile)
	convert(pathToFile, "flac")
end

def to_wav(pathToFile)
	convert(pathToFile, "wav")
end

SubzGenerator/app/controllers/video_services/translate.rb
require 'yaml'
require 'json'

def transform_lang(language)
	hash = YAML.load(File.read(Rails.root.to_s + "/app/controllers/video_services/config_lang.yml"))
	hash[language].to_s
end

def translatee(text, language)
	response = `curl -X POST -H "Content-type: application/json" -H "Authorization: LC apiKey=B9nsEIqZ6zrODSu%2BxPJw2A%3D%3D" -d '{"text": "#{text}", "from":"eng", "to":"#{transform_lang(language)}"}' https://lc-api.sdl.com/translate`
	JSON.parse(response)["translation"]
end

SubzGenerator/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

SubzGenerator/app/helpers/application_helper.rb
module ApplicationHelper
  def javascript(*files)
    content_for(:head) { javascript_include_tag('/assets/jquery.js') }
    content_for(:head) { javascript_include_tag('/assets/cable.js') }
    content_for(:head) { javascript_include_tag('/assets/custom-min.js') }
    content_for(:head) { javascript_include_tag('/assets/init.js') }
    content_for(:head) { javascript_include_tag('/assets/materialize.js') }
    content_for(:head) { javascript_include_tag('/assets/materialize.min.js') }
    content_for(:head) { javascript_include_tag('/assets/modernizr.js') }
    content_for(:head) { javascript_include_tag('/assets/plugin-min.js') }
    content_for(:head) { javascript_include_tag('/assets/forms.js') }
  end
end

SubzGenerator/app/helpers/download_srt_helper.rb
module DownloadSrtHelper
end

SubzGenerator/app/helpers/file_upload_helper.rb
module FileUploadHelper
end

SubzGenerator/app/helpers/welcome_helper.rb
module WelcomeHelper
end

SubzGenerator/app/views/file_upload/index.html.erb
<link href="/assets/file_upload.scss" media="screen" rel="stylesheet" />

<hgroup>
  <h1>Generate Subtitles</h1>
</hgroup>

<form accept-charset="UTF-8" method="post" enctype="multipart/form-data">
	<input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
		<div class="row">
			<div class="col col-lg-4">
				<%= image_tag("video.png", size: "175x175") %>
			</div>
			<div class="col col-lg-4">
				<%= image_tag("rightArrow.png", size: "175x175") %>
			</div>
			<div class="col col-lg-4">
				<%= image_tag("subtitle.png", size: "175x175") %>
			</div>
		</div>

    <% @lang = ["Bulgarian", "Hungarian", "English", "Russian", "German"] %>
    <%= select_tag 'upload[lang]', options_for_select([["Select language" , "" ]] + @lang.to_a.sort!), class: 'form-control', :required => true %>
		<%= file_field_tag 'upload[file]', class: 'form-control', :required => true, accept: 'video/mp4' %>
		<%= submit_tag "Get subtitles", class: 'button buttonBlue' %>
</form>

SubzGenerator/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SubzGenerator</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="/assets/style.css" media="screen" rel="stylesheet" />
    <link href="/assets/materialize.css" media="screen" rel="stylesheet" />
    <link href="/assets/materialize.min.css" media="screen" rel="stylesheet" />
    <link href="/assets/font-awesome.min.css" media="screen" rel="stylesheet" />
    <link href="/assets/custom-min.css" media="screen" rel="stylesheet" />
    <link href="/assets/plugin-min.css" media="screen" rel="stylesheet" />
  </head>

  <body>
  <div id="loader-wrapper">
      <div id="loader"></div>

      <div class="loader-section section-left"></div>
      <div class="loader-section section-right"></div>

  </div>

  <!--Navigation-->
   <div class="navbar-fixed">
      <nav id="nav_f" class="default_color" role="navigation">
          <div class="container">
              <div class="nav-wrapper">
              <a href="/" id="logo-container" class="brand-logo">SubzGenerator</a>
                  <ul class="right hide-on-med-and-down">
                      <% if user_signed_in? %>
                        <li><%= link_to('Generate subtitles', :controller => :file_upload, :method => :delete) %></li>
                      <% end %>
                      <li><a href="#intro">About us</a></li>
                      <li><a href="#team">Contact</a></li>
                      <% if user_signed_in? %>
                        <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
                      <% else %>
                        <li><%= link_to('Login', new_user_session_path) %></li>
                      <% end %>
                  </ul>
                  <ul id="nav-mobile" class="side-nav">
                    <% if user_signed_in? %>
                      <li><%= link_to('Generate subtitles', :controller => :file_upload, :method => :delete) %></li>
                    <% end %>
                    <li><a href="#intro">About us</a></li>
                    <li><a href="#team">Contact</a></li>
                    <% if user_signed_in? %>
                      <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
                    <% else %>
                      <%= link_to('Login', new_user_session_path)  %>
                    <% end %>
                  </ul>
              <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="mdi-navigation-menu"></i></a>
              </div>
          </div>
      </nav>
  </div>
    <%= yield %>
    <% javascript 'plugin-min.js' %>
    <% javascript 'custom-min.js' %>
  </body>
</html>

SubzGenerator/app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

SubzGenerator/app/views/welcome/index.html.erb
<div class="section no-pad-bot" id="index-banner">
    <div class="container">
        <h1 class="text_h center header cd-headline letters type" >
            <span style="display: block;">I Love</span>
            <span class="cd-words-wrapper waiting">
                <b class="is-visible" style="display: block;">videos</b>
                <b style="display: block;">movies</b>
                <b style="display: block;">seriece </b>
            </span>
        </h1>
    </div>
</div>
<!--Intro and service-->
<div id="intro" class="section scrollspy">
    <div class="container">
        <div class="row">
            <div  class="col s12">
                  <h2 class="center header text_h2"> Just upload your movie or video clip <span class="span_h2"> Easy as that </span>, no extra download no headeags <span class="span_h2">, on the go.</span> </h2>
            </div>

            <div  class="col s12 m4 l4">
                <div class="center promo promo-example">
                  <%= image_tag("/assets/generate.png",  alt: "", class: "mdi-image-flash-on", size: "175x175") %>
                  <h5 class="promo-caption">Realtime generating.</h5>
                  <p class="light center">Generating a srt.file with your subtitles.</p>
                </div>
            </div>
            <div class="col s12 m4 l4">
                <div class="center promo promo-example">
                  <%= image_tag("/assets/lazy.png",  alt: "", class: "mdi-image-flash-on", size: "175x175") %>
                  <h5 class="promo-caption">No extra work</h5>
                  <p class="light center">Auto synchronizing with your movie just sitback and relax</p>
                </div>
            </div>
            <div class="col s12 m4 l4">
                <div class="center promo promo-example">
                  <%= image_tag("/assets/responsive.png",  alt: "", class: "mdi-image-flash-on", size: "250x175") %>
                  <h5 class="promo-caption">Fully responsive</h5>
                  <p class="light center">Satisfying your needs</p>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="section scrollspy" id="team">
    <div class="container">
        <h2 class="header text_b"> Our Team </h2>
        <div class="row">
            <div class="col s12 m4">
                <div class="card card-avatar">
                    <div class="waves-effect waves-block waves-light">
                        <img class="activator" src="https://scontent.xx.fbcdn.net/v/t1.0-9/17103723_1120075034782215_7419774195789019289_n.jpg?oh=10d881e64d8572dda50185cd63062f15&oe=59E337C4">
                    </div>
                    <div class="card-content">
                        <span class="card-title activator grey-text text-darken-4">Lyubomir Yankov<br/>
                            <small><em><a class="red-text text-darken-1" href="#">CEO</a></em></small></span>
                        <p>
                            <a class="blue-text text-lighten-2" href="https://www.facebook.com/joash.c.pereira">
                                <i class="fa fa-facebook-square"></i>
                            </a>
                            <a class="blue-text text-lighten-2" href="https://twitter.com/im_joash">
                                <i class="fa fa-twitter-square"></i>
                            </a>
                            <a class="blue-text text-lighten-2" href="https://plus.google.com/u/0/+JoashPereira">
                                <i class="fa fa-google-plus-square"></i>
                            </a>
                            <a class="blue-text text-lighten-2" href="https://www.linkedin.com/in/joashp">
                                <i class="fa fa-linkedin-square"></i>
                            </a>
                        </p>
                    </div>
                </div>
            </div>
            <div class="col s12 m4">
                <div class="card card-avatar">
                    <div class="waves-effect waves-block waves-light">
                        <img class="activator" src="https://scontent.xx.fbcdn.net/v/t34.0-12/18902571_1893116234239834_549618097_n.png?oh=5693de3ad59a7f3f1cd997712beb7ecc&oe=59356FAA">
                    </div>
                    <div class="card-content">
                        <span class="card-title activator grey-text text-darken-4">Martin Savov<br/>
                            <small><em><a class="red-text text-darken-1" href="#">Designer</a></em></small>
                        </span>
                        <p>
                            <a class="blue-text text-lighten-2" href="https://www.facebook.com/joash.c.pereira">
                                <i class="fa fa-facebook-square"></i>
                            </a>
                            <a class="blue-text text-lighten-2" href="https://twitter.com/im_joash">
                                <i class="fa fa-twitter-square"></i>
                            </a>
                            <a class="blue-text text-lighten-2" href="https://plus.google.com/u/0/+JoashPereira">
                                <i class="fa fa-google-plus-square"></i>
                            </a>
                            <a class="blue-text text-lighten-2" href="https://www.linkedin.com/in/martin-savov-b6b322144/">
                              <i class="fa fa-linkedin-square"></i>
                            </a>
                        </p>
                    </div>
                </div>
            </div>
            <div class="col s12 m4">
                <div class="card card-avatar">
                    <div class="waves-effect waves-block waves-light">
                        <img class="activator" src="https://scontent.xx.fbcdn.net/v/t1.0-9/18557192_1413194035385337_3118534449777745490_n.jpg?oh=ee3921e1a81eaa570670906d38620a43&oe=59A3D8EA">
                    </div>
                    <div class="card-content">
                        <span class="card-title activator grey-text text-darken-4">
                            Vladimir Katrandzhiev <br/>
                            <small><em><a class="red-text text-darken-1" href="#">CMO</a></em></small></span>
                        <p>
                            <a class="blue-text text-lighten-2" href="https://www.facebook.com/joash.c.pereira">
                                <i class="fa fa-facebook-square"></i>
                            </a>
                            <a class="blue-text text-lighten-2" href="https://twitter.com/im_joash">
                                <i class="fa fa-twitter-square"></i>
                            </a>
                            <a class="blue-text text-lighten-2" href="https://plus.google.com/u/0/+JoashPereira">
                                <i class="fa fa-google-plus-square"></i>
                            </a>
                            <a class="blue-text text-lighten-2" href="https://www.linkedin.com/in/joashp">
                                <i class="fa fa-linkedin-square"></i>
                            </a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<footer id="contact" class="page-footer default_color scrollspy">
    <div class="container">
        <div class="row">
            <div class="col l3 s12">
                <h5 class="white-text">Social</h5>
                <ul>
                    <li>
                        <a class="white-text" href="https://www.facebook.com/martin.savov.501">
                            <i class="small fa fa-facebook-square white-text"></i> Facebook
                        </a>
                    </li>
                    <li>
                        <a class="white-text" href="https://git.fhict.nl/I358717">
                            <i class="small fa fa-github-square white-text"></i> Github
                        </a>
                    </li>
                    <li>
                        <a class="white-text" href="https://www.linkedin.com/in/martin-savov-b6b322144/">
                            <i class="small fa fa-linkedin-square white-text"></i> Linkedin
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="footer-copyright default_color">
        <div class="container">
            Made by <a class="white-text" href="#">Us</a>. With <3</a>
        </div>
    </div>
</footer>